steps:
  - id: prepare-env
    name: node:16.16.0
    entrypoint: cp
    args: ['env-min', '.env']
  - id: npm-ci
    name: node:16.16.0
    entrypoint: npm
    args: ['ci', "--legacy-peer-deps"]
  - id: compile
    name: node:16.16.0
    entrypoint: npx
    args: ['hardhat', 'compile', '--force']
  - id: test
    name: node:16.16.0
    entrypoint: npx
    args: ['hardhat', 'test']
    env:
      - IPFS_GATEWAY_URI="https://ipfs.dsla.network"