steps:
  - id: prepare-env
    name: node:lts-stretch
    entrypoint: cp
    args: ['env-min', '.env']
  - id: npm-ci
    name: node:lts-stretch
    entrypoint: npm
    args: ['ci', "--legacy-peer-deps"]
  - id: compile
    name: node:lts-stretch
    entrypoint: npx
    args: ['hardhat', 'compile']
  - id: test
    name: node:lts-stretch
    entrypoint: npx
    args: ['hardhat', 'test']
