/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EthereumERC20 } from "./EthereumERC20";
export type { FantomERC20 } from "./FantomERC20";
export type { PolygonERC20 } from "./PolygonERC20";
