/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EthereumERC20__factory } from "./EthereumERC20__factory";
export { FantomERC20__factory } from "./FantomERC20__factory";
export { PolygonERC20__factory } from "./PolygonERC20__factory";
