/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface IMessengerRegistryInterface extends utils.Interface {
  functions: {
    "registerMessenger(address,address,string)": FunctionFragment;
    "registeredMessengers(address)": FunctionFragment;
    "setSLARegistry()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "registerMessenger"
      | "registeredMessengers"
      | "setSLARegistry"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "registerMessenger",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredMessengers",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setSLARegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "registerMessenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredMessengers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSLARegistry",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IMessengerRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMessengerRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    registerMessenger(
      callerAddress_: PromiseOrValue<string>,
      messengerAddress_: PromiseOrValue<string>,
      specificationUrl_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registeredMessengers(
      messengerAddress_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setSLARegistry(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  registerMessenger(
    callerAddress_: PromiseOrValue<string>,
    messengerAddress_: PromiseOrValue<string>,
    specificationUrl_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registeredMessengers(
    messengerAddress_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setSLARegistry(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    registerMessenger(
      callerAddress_: PromiseOrValue<string>,
      messengerAddress_: PromiseOrValue<string>,
      specificationUrl_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    registeredMessengers(
      messengerAddress_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setSLARegistry(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    registerMessenger(
      callerAddress_: PromiseOrValue<string>,
      messengerAddress_: PromiseOrValue<string>,
      specificationUrl_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registeredMessengers(
      messengerAddress_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setSLARegistry(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    registerMessenger(
      callerAddress_: PromiseOrValue<string>,
      messengerAddress_: PromiseOrValue<string>,
      specificationUrl_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registeredMessengers(
      messengerAddress_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setSLARegistry(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
