/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Query } from "./IERC20Query";
export type { IMessenger } from "./IMessenger";
export type { IMessengerRegistry } from "./IMessengerRegistry";
export type { IPeriodRegistry } from "./IPeriodRegistry";
export type { ISLARegistry } from "./ISLARegistry";
export type { ISLORegistry } from "./ISLORegistry";
export type { IStakeRegistry } from "./IStakeRegistry";
