/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Details } from "./Details";
export type { MessengerRegistry } from "./MessengerRegistry";
export type { PeriodRegistry } from "./PeriodRegistry";
export type { SLA } from "./SLA";
export type { SLARegistry } from "./SLARegistry";
export type { SLORegistry } from "./SLORegistry";
export type { StakeRegistry } from "./StakeRegistry";
export type { Staking } from "./Staking";
export type { DToken } from "./DToken";
