version: "3.5"
services:
  ipfs-daemon:
    container_name: ipfs-daemon
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '4001:4001'
      - '5001:5001'
      - '8080:8080'
    networks:
      - dsla-test
    volumes:
      - ./data:/data/ipfs
    entrypoint: ipfs
    command: daemon --writable
  ipfs-server:
    image: nginx:stable-alpine
    container_name: ipfs-server
    depends_on:
      - ipfs-daemon
    ports:
      - 8888:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dsla-test
networks:
  dsla-test:
    name: ipfs-network

volumes:
  ipfs:
