/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as assetFloor from "./asset-floor";
export * as assetPeg from "./asset-peg";
export * as base from "./base";
export * as inflationRate from "./inflation-rate";
export * as stakingApr from "./staking-apr";
export * as stakingUptime from "./staking-uptime";
