version: "3.5"
services:
  postgres:
    container_name: postgres-dsla-env
    image: postgres:13.1
    volumes:
      - ./postgres/develop/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chainlink
    networks:
      - dsla-test

  chainlink:
    container_name: chainlink-dsla-env
    image: smartcontract/chainlink:0.9.6
    ports:
      - 6688:6688
    volumes:
      - ./chainlink:/chainlink
      - ./chainlink/.api:/chainlink/.api
      - ./chainlink/.password:/chainlink/.password
    environment:
      - ROOT=/chainlink
      - ETH_CHAIN_ID=1337
      - LOG_LEVEL=info
      - MIN_INCOMING_CONFIRMATIONS=0
      - MIN_OUTGOING_CONFIRMATIONS=0
      - LINK_CONTRACT_ADDRESS=0xC4bC1f775dB36c07b0bC506cbB83fCe12E182053
      - CHAINLINK_TLS_PORT=0
      - SECURE_COOKIES=false
      - GAS_UPDATER_ENABLED=true
      - ALLOW_ORIGINS=*
      - ETH_URL=ws://host.docker.internal:8545
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/chainlink?sslmode=disable
      - DEFAULT_HTTP_TIMEOUT=200s

    command: local n -p /chainlink/.password -a /chainlink/.api
    networks:
      - dsla-test
    depends_on:
      - postgres
    restart: on-failure

networks:
  dsla-test:
    name: dsla-local-environment

volumes:
  postgres:
  chainlink:
