version: "3.5"
services:
  postgres:
    container_name: postgres-harmony-dsla-env
    image: postgres:13.1
    volumes:
      - ./postgres/harmonytestnet/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chainlink
    networks:
      - dsla-harmony-test

  chainlink:
    container_name: chainlink-harmony-dsla-env
    image: smartcontract/chainlink:0.9.6
    ports:
      - 6688:6688
    volumes:
      - ./chainlink:/chainlink
      - ./chainlink/.api:/chainlink/.api
      - ./chainlink/.password:/chainlink/.password
    environment:
      - ROOT=/chainlink
      - ETH_CHAIN_ID=1666700000
      - LOG_LEVEL=info
      - MIN_INCOMING_CONFIRMATIONS=0
      - MIN_OUTGOING_CONFIRMATIONS=0
      - LINK_CONTRACT_ADDRESS=0x0290FB167208Af455bB137780163b7B7a9a10C16
      - CHAINLINK_TLS_PORT=0
      - SECURE_COOKIES=false
      - GAS_UPDATER_ENABLED=true
      - ALLOW_ORIGINS=*
      - ETH_URL=wss://ws.s0.b.hmny.io
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/chainlink?sslmode=disable
      - DEFAULT_HTTP_TIMEOUT=200s

    command: local n -p /chainlink/.password -a /chainlink/.api
    networks:
      - dsla-harmony-test
    depends_on:
      - postgres
    restart: on-failure

networks:
  dsla-harmony-test:
    name: dsla-local-harmony-environment

volumes:
  postgres:
  chainlink:
