/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetFloor from "./asset-floor";
export type { assetFloor };
import type * as assetPeg from "./asset-peg";
export type { assetPeg };
import type * as base from "./base";
export type { base };
import type * as inflationRate from "./inflation-rate";
export type { inflationRate };
import type * as stakingApr from "./staking-apr";
export type { stakingApr };
import type * as stakingUptime from "./staking-uptime";
export type { stakingUptime };
