name: DSLA DTK integration testing
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
      - run: cp 'env-min' .env
        name: prepare-env
      - run: npm ci --legacy-peer-deps
        name: npm ci
      - name: Compile
        run: npx hardhat compile --force
      - name: Test
        run: IPFS_GATEWAY_URI="https://ipfs.dsla.network" npx hardhat test