name: DSLA DTK integration testing
on: [push]
jobs:
  run-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: cp 'env-min' .env
        name: prepare-env
      - run: npm i
        name: npm i
      - name: Test
        run: IPFS_GATEWAY_URI="https://ipfs.dsla.network" npx hardhat test
